version: '3.7'
services:
  app:
    build:
      context: .
    ports:
      - 8080:8080

    volumes:
#      - ./src:/home/UPweb/src
      - ./src/main/webapp/data:/webapps/UPweb/data
    links:
     - mysql

  mysql:
    image: mysql:latest
    # container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: up_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
       - 3306:3306
